---
- name: PHP-FPM | Installation
  apk:
     name=php5-fpm,php5-mysql,php5-opcache
     state=present
     update_cache=yes

- name: PHP-FPM | Setting config file src=php-fpm.conf
  template:
     src=php-fpm.conf
     dest=/etc/php
